<a href="https://colab.research.google.com/github/udaykiran811/PDS-10-2303A51523-/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [88, 76, 92],
    [60, 65, 70],
    [95, 89, 94],
    [82, 79, 85]
])

print("Student Marks (2D Array):\n", marks)

avg_marks = np.mean(marks)
min_marks = np.min(marks)
max_marks = np.max(marks)

print("\nAverage Marks (overall):", avg_marks)
print("Minimum Marks (overall):", min_marks)
print("Maximum Marks (overall):", max_marks)

print("\nSubject-wise Average:", np.mean(marks, axis=0))
print("Subject-wise Min:", np.min(marks, axis=0))
print("Subject-wise Max:", np.max(marks, axis=0))

print("\nMarks of Student 2:", marks[1])
print("Marks of first 3 students:\n", marks[:3])

above_80 = marks > 80
print("\nBoolean mask (scores > 80):\n", above_80)

students_above_80 = marks[np.any(marks > 80, axis=1)]
print("Students with at least one subject > 80:\n", students_above_80)

reshaped = marks.T
print("\nReshaped Array (Subject-wise performance):\n", reshaped)

print("\nAnalysis:")
print("1. Student 4 consistently scores highest across subjects.")
print("2. Student 3 has the lowest overall performance.")
print("3. Science seems slightly tougher as average is lower compared to Math & English.")
print("4. Many students have marks > 80, showing strong performance in multiple subjects.")


Student Marks (2D Array):
 [[78 85 90]
 [88 76 92]
 [60 65 70]
 [95 89 94]
 [82 79 85]]

Average Marks (overall): 81.86666666666666
Minimum Marks (overall): 60
Maximum Marks (overall): 95

Subject-wise Average: [80.6 78.8 86.2]
Subject-wise Min: [60 65 70]
Subject-wise Max: [95 89 94]

Marks of Student 2: [88 76 92]
Marks of first 3 students:
 [[78 85 90]
 [88 76 92]
 [60 65 70]]

Boolean mask (scores > 80):
 [[False  True  True]
 [ True False  True]
 [False False False]
 [ True  True  True]
 [ True False  True]]
Students with at least one subject > 80:
 [[78 85 90]
 [88 76 92]
 [95 89 94]
 [82 79 85]]

Reshaped Array (Subject-wise performance):
 [[78 88 60 95 82]
 [85 76 65 89 79]
 [90 92 70 94 85]]

Analysis:
1. Student 4 consistently scores highest across subjects.
2. Student 3 has the lowest overall performance.
3. Science seems slightly tougher as average is lower compared to Math & English.
4. Many students have marks > 80, showing strong performance in multiple subjects.


In [ ]:
import pandas as pd

data = {
    "Employee_ID": ["E001", "E002", "E003", "E004", "E005", "E006", "E007"],
    "Name": ["Alice Johnson", "Bob Smith", "Charlie Lee", "Diana Patel", "Ethan Brown", "Fiona Davis", "George Wilson"],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing", "Finance", "HR"],
    "Salary": [48000, 72000, 51000, 45000, 60000, 52000, 80000]
}

df = pd.DataFrame(data)

df.to_csv("employees.csv", index=False)

print("Sample dataset created and saved as employees.csv")
print(df)


Sample dataset created and saved as employees.csv
  Employee_ID           Name Department  Salary
0        E001  Alice Johnson         HR   48000
1        E002      Bob Smith         IT   72000
2        E003    Charlie Lee    Finance   51000
3        E004    Diana Patel         IT   45000
4        E005    Ethan Brown  Marketing   60000
5        E006    Fiona Davis    Finance   52000
6        E007  George Wilson         HR   80000
